---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: k8s-pipe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: do-block-storage
