apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: k8s-pipe
spec:
  containers:
   - name: maven
     image: maven:3.8.3-adoptopenjdk-11
     command:
     - cat
     tty: true
     volumeMounts:
      - name: maven-cache
        mountPath: /root/.m2/repository
   - name: git
     image: bitnami/git:latest
     command:
     - cat
     tty: true
   - name: sonarcli
     image: sonarsource/sonar-scanner-cli
     command:
     - cat
     tty: true
   - name: dockercli
     image: docker:latest
     command:
     - cat
     tty: true
     volumeMounts:
     - name: docker-sock
       mountPath: /var/run/docker.sock
  volumes:
   - name: maven-cache
     persistentVolumeClaim:
       claimName: myclaim
   - name: docker-sock
     hostPath: 
       path: /var/run/docker.sock