apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: maven
    image: maven:3.8.3-adoptopenjdk-11
    command:
    - cat
    tty: true
    #volumeMounts:
    #  - name: maven-cache
    #   mountPath: /root/.m2/repository
  - name: git
    image: bitnami/git:latest
    command:
    - cat
    tty: true
  #volumes:
  #- name: maven-cache
   # persistentVolumeClaim:
     # className: myclaim